import gradio as gr
from tensorflow.keras.models import load_model
import cv2
from PIL import Image
import numpy as np

# Load the saved model (ensure TensorFlow 2.x compatibility)
model = load_model('traffic_sign_recognizer.h5')

# Traffic sign classes
classes = {
    0: '''Speed limit (20km/h)\n\nThis road sign indicates a strict speed limit of 20 kilometers per hour. Such low speed limits are typically found in areas with heavy pedestrian traffic, such as school zones or residential areas. It's crucial for rivers to adhere to this limit to ensure the safety of pedestrians and other road users in these congested areas.''',
    1: '''Speed limit (30km/h)\n\nWhen you encounter this sign, it means you must maintain a speed of no more than 30 kilometers per hour. These speed limits are often seen in urban areas where there are numerous intersections, pedestrian crossings, and other potential hazards. Slower speeds in such environments reduce the risk of accidents and give drivers more time to react to unexpected situations.''',
    2: '''Speed limit (50km/h)\n\nThis sign indicates a speed limit of 50 kilometers per hour. It's a common limit on urban roads and some suburban streets. At this speed, drivers can maintain better control of their vehicles and have adequate time to react to traffic signals, pedestrians, and other vehicles.''',
    3: '''Speed limit (60km/h)\n\nA speed limit of 60 kilometers per hour is typically found on urban arterial roads and some rural highways. It strikes a balance between allowing vehicles to travel at a reasonable speed while ensuring safety for all road users. Drivers should pay attention to this limit and adjust their speed accordingly to maintain safe driving conditions.''',
    4: '''Speed limit (70km/h)\n\nThis sign indicates a speed limit of 70 kilometers per hour, often found on rural roads and highways where conditions allow for higher speeds. However, drivers should always be mindful of factors such as weather, road conditions, and traffic volume, and adjust their speed accordingly to ensure safe travel.''',
    5: '''Speed limit (80km/h)\n\nSimilar to the previous sign, this one designates a speed limit of 80 kilometers per hour. It's commonly seen on highways and other major roads where conditions permit higher speeds. However, drivers must exercise caution and adhere to this limit to prevent accidents and ensure the safety of themselves and others on the road.''',
    6: '''End of speed limit (80km/h)\n\nThis sign marks the end of a specific speed limit zone, in this case, the 80 kilometers per hour limit. Once past this sign, drivers can resume driving at speeds dictated by general speed limits unless otherwise posted. It's important for drivers to be aware of changes in speed limits to avoid speeding violations and maintain safe driving practices.''',
    7: '''Speed limit (100km/h)\n\nWhen you see this sign, it means you're entering a zone with a speed limit of 100 kilometers per hour. These limits are typically found on highways and expressways where conditions allow for faster travel. However, drivers must still exercise caution and be mindful of other road users to ensure safe travels.''',
    8: '''Speed limit (120km/h)\n\nThis sign indicates a high-speed limit of 120 kilometers per hour, commonly found on divided highways and motorways. At this speed, drivers must maintain full control of their vehicles and be vigilant of changing road conditions, merging traffic, and other potential hazards. Adherence to this limit ensures safe and efficient travel on these high-speed roadways.''',
    9: ''''No passing\n\nThis sign indicates that passing is prohibited in the upcoming area. Passing is a maneuver where a driver overtakes another vehicle traveling in the same direction. Prohibiting passing in certain areas is often done to ensure safety, especially where visibility is limited, or road conditions make passing hazardous. Drivers should adhere to this restriction to avoid accidents and maintain the flow of traffic.''',
    10: '''No passing veh over 3.5 tons\n\nThis road sign indicates a specific restriction on passing for vehicles weighing over 3.5 tons. Passing restrictions for heavier vehicles are often implemented to ensure safety, as these vehicles require more time and space to accelerate and decelerate compared to smaller vehicles. Adherence to this restriction helps maintain the flow of traffic and reduces the risk of accidents, especially on roads with narrow lanes or limited visibility.''',
    11: '''Right-of-way at intersection\n\nThis sign indicates that drivers approaching an intersection must yield the right-of-way to vehicles already within the intersection. Right-of-way rules are crucial for maintaining smooth traffic flow and preventing collisions at intersections. Drivers must be attentive to other vehicles and follow the appropriate right-of-way rules to navigate intersections safely and efficiently.''',
    12: '''Priority road\n\nWhen you encounter this sign, it indicates that you are approaching a priority road, where vehicles have the right-of-way over intersecting roads. Priority roads are typically main thoroughfares or major highways, and drivers on secondary roads must yield to traffic on the priority road. Adherence to right-of-way rules is essential for preventing accidents and ensuring the orderly movement of traffic.''',
    13: '''Yield\n\nThis triangular sign with a red border and white interior indicates that drivers approaching a specific point must yield the right-of-way to vehicles on the intersecting road. Yield signs are often placed at entrances to roundabouts, intersections with limited visibility, or areas where merging traffic needs to yield. Drivers must be prepared to stop if necessary and yield to oncoming traffic to prevent collisions and maintain traffic flow.''',
    14: '''Stop\n\nThe octagonal shape and red color of this sign indicate that drivers approaching an intersection or a specific point must come to a complete stop before proceeding. Stop signs are placed at intersections where visibility is limited or traffic conditions require vehicles to stop to yield the right-of-way. Drivers must obey the stop sign, check for cross traffic or pedestrians, and proceed only when it is safe to do so.''',
    15: '''No vehicles\n\nThis sign indicates a restriction on all types of vehicles beyond this point. Such restrictions are often found in pedestrian-only zones, bicycle lanes, or areas where vehicle access is prohibited for safety or environmental reasons. Drivers must respect these restrictions to avoid fines and ensure the safety of pedestrians and other road users.''',
    16: '''Veh > 3.5 tons prohibited\n\nThis sign indicates that vehicles weighing over 3.5 tons are prohibited from entering beyond this point. Such restrictions may be imposed on certain roads to prevent damage to infrastructure, reduce congestion, or improve safety conditions. Drivers of heavy vehicles must obey these restrictions and find alternative routes to reach their destination.''',
    17: '''No entry\n\nThe circular shape and red border of this sign indicate that entry is prohibited beyond this point. No entry signs are often used to designate one-way streets, restricted access areas, or private property where unauthorized entry is not allowed. Drivers must obey these signs to avoid legal consequences and ensure the safety and security of restricted areas.''',
    18: '''General caution\n\nThis sign serves as a warning to drivers to exercise caution and be vigilant for potential hazards ahead. It is often used to alert drivers to conditions such as sharp curves, steep inclines, or changes in road surface. Drivers must reduce speed, maintain control of their vehicles, and be prepared to react to unexpected situations when encountering a general caution sign.''',
    19: '''Dangerous curve left\n\nThis sign warns drivers of a dangerous curve to the left ahead. Dangerous curves may pose risks such as reduced visibility, sharp turns, or adverse road conditions. Drivers must approach such curves at a safe speed, stay in their lane, and be prepared for sudden changes in direction to navigate the curve safely.''',
    20: '''Dangerous curve right\n\nSimilar to the previous sign, this warns drivers of a dangerous curve, but this time to the right. These curves often require extra caution due to factors like limited visibility, sharp turns, or adverse road conditions. Drivers should reduce speed, stay focused, and maintain control of their vehicles to safely navigate the curve.''',
    21: '''Double curve\n\nThis sign indicates that there are consecutive curves in the road, typically in the same direction. Double curves can be challenging to navigate, especially if they're tight or if visibility is limited. Drivers should anticipate the upcoming curves, adjust their speed accordingly, and maintain proper lane position to safely negotiate both curves.''',
    22: '''Bumpy road\n\nThis sign warns drivers of a road surface that is uneven or rough, often due to potholes, pavement deterioration, or construction work. Bumpy roads can affect vehicle stability and comfort, so drivers should reduce speed and maintain a firm grip on the steering wheel to ensure control and avoid damage to their vehicle.''',
    23: '''Slippery road\n\nWhen this sign is posted, it indicates that the road surface may be slippery due to various factors such as rain, ice, snow, or oil spills. Slippery roads reduce traction and increase the risk of skidding or losing control of the vehicle. Drivers should exercise extreme caution, reduce speed, and avoid sudden maneuvers to prevent accidents on slippery surfaces.''',
    24: '''Road narrows on the right\n\nThis sign warns drivers that the roadway ahead will narrow, typically due to construction, a merge lane ending, or an obstruction on the right side of the road. Drivers should prepare to merge left if necessary and be mindful of other vehicles as the road narrows to ensure smooth traffic flow and prevent collisions.''',
    25: '''Road work\n\nWhen drivers encounter this sign, it indicates that road construction or maintenance activities are underway ahead. Road work zones can present various hazards such as uneven road surfaces, lane closures, and construction equipment. Drivers should reduce speed, follow any posted instructions or detours, and be prepared for sudden changes in traffic patterns.''',
    26: '''Traffic signals\n\nThis sign alerts drivers to the presence of traffic signals ahead, such as traffic lights or flashing beacons. Traffic signals regulate the flow of traffic at intersections and other critical points on the road. Drivers should be prepared to obey the signals, stop if necessary, and proceed only when it is safe and legal to do so.''',
    27: '''Pedestrians\n\nWhen this sign is posted, it indicates the presence of pedestrians or pedestrian crossings ahead. Pedestrians have the right-of-way at designated crossings, and drivers must yield to them to ensure their safety. Drivers should be vigilant, reduce speed in pedestrian-heavy areas, and always be prepared to stop for pedestrians crossing the road.''',
    28: '''Children crossing\n\nSimilar to the previous sign, this one specifically warns drivers to watch out for children crossing the road. Children may be less predictable than adults and may dart into the road unexpectedly. Drivers should exercise extreme caution, reduce speed, and be prepared to stop to prevent accidents involving children.''',
    29: '''Bicycles crossing\n\nThis sign alerts drivers to the presence of a designated crossing for bicycles. Bicycles are considered vehicles and have the right-of-way at these crossings. Drivers should watch for cyclists approaching the crossing, yield to them as necessary, and provide them with sufficient space to cross safely.''',
    30: '''Beware of ice/snow\n\nThis sign warns drivers of potentially hazardous road conditions due to ice or snow accumulation. Driving on icy or snowy roads reduces traction and increases the risk of skidding or losing control of the vehicle. Drivers should exercise extreme caution, reduce speed significantly, and avoid sudden maneuvers to safely navigate icy or snowy stretches of road.''',
    31: '''Wild animals crossing\n\nWhen this sign is posted, it indicates that drivers should be cautious of wild animals crossing the road ahead. Wildlife crossings are common in rural areas or near natural habitats, where animals may venture onto the road, increasing the risk of collisions. Drivers should reduce speed, especially in areas with dense vegetation or wildlife habitats, and be prepared to stop for crossing animals.''',
    32: '''End speed + passing limits\n\nThis sign marks the end of specific speed and passing restrictions that were previously in effect. Once past this sign, drivers are no longer bound by those restrictions and can resume driving at speeds dictated by general speed limits unless otherwise posted. It's essential for drivers to be aware of changes in speed and passing regulations to adjust their driving behavior accordingly.''',
    33: '''Turn right ahead\n\nThis sign informs drivers of an upcoming right turn in the road. Drivers should prepare to slow down, check their mirrors and blind spots, and signal their intention to turn right in advance. Proper positioning within the lane is crucial to safely negotiate the turn without encroaching on other lanes or endangering pedestrians or cyclists.''',
    34: '''Turn left ahead\n\nSimilar to the previous sign, this one indicates an upcoming left turn in the road. Drivers should reduce speed, check for oncoming traffic, pedestrians, or cyclists, and signal their intention to turn left in advance. Proper lane positioning and awareness of surrounding road users are essential for executing the left turn safely.''',
    35: '''Ahead only\n\nThis sign indicates that the road ahead continues straight, and there are no options for turning or diverging from the current path. Drivers should stay in the designated lane and continue straight ahead without changing direction. It's essential to maintain a steady speed and be mindful of other vehicles sharing the roadway to ensure safe travel.''',
    36: '''Go straight or right\n\nWhen drivers encounter this sign, it indicates that they have the option to continue straight ahead or make a right turn at the upcoming intersection or junction. Drivers should choose the appropriate lane based on their intended direction and signal their intentions in advance. Proper lane positioning and awareness of other road users are essential for safe maneuvering.''',
    37: '''Go straight or left\n\nSimilar to the previous sign, this one indicates that drivers have the option to continue straight ahead or make a left turn at the upcoming intersection or junction. Drivers should select the appropriate lane based on their intended direction and signal their intentions clearly. Maintaining proper lane discipline and yielding to other road users when necessary are essential for safe navigation.''',
    38: '''Keep right\n\nThis sign instructs drivers to keep to the right side of the road or lane. Keeping right is essential for maintaining the smooth flow of traffic, especially on multi-lane roads or highways. Drivers should adhere to this instruction unless passing slower vehicles or making a left turn at an upcoming intersection or junction.''',
    39: '''Keep left\n\nContrary to the previous sign, this one instructs drivers to keep to the left side of the road or lane. Keeping left is necessary in countries where driving occurs on the left side of the road or when approaching specific situations such as diverging lanes or toll booths. Drivers should follow this instruction to maintain orderly traffic flow and prevent accidents.''',
    40: '''Roundabout mandatory\n\nThis sign indicates that drivers must enter and travel through a roundabout ahead. Roundabouts are circular intersections designed to improve traffic flow and safety by requiring vehicles to yield to traffic already in the roundabout before entering. Drivers should approach the roundabout at a safe speed, yield to circulating traffic, and choose the appropriate lane based on their intended exit.''',
    41: '''End of no passing\n\nThis sign marks the end of a section of road where passing was previously prohibited. Once past this sign, drivers are permitted to resume passing slower vehicles if safe and legal to do so. It's essential for drivers to exercise caution when passing and ensure that they have adequate visibility and space to complete the maneuver safely.''',
    42: '''End no passing veh > 3.5 tons\n\nSimilar to the previous sign, this one indicates the end of a section of road where passing for vehicles weighing over 3.5 tons was previously prohibited. Once past this sign, drivers of heavier vehicles are permitted to resume passing if safe and legal to do so. Drivers should remain attentive to road conditions and other traffic to ensure safe passing maneuvers.'''
}

def preprocess_image(image):
    """Preprocess the input image."""
    image = np.array(image)  # Convert to NumPy array (assuming RGB)
    image = cv2.resize(image, (30, 30))  # Resize to expected height and width
    image = image.astype('float32') / 255.0  # Normalize pixel values to [0, 1]
    return np.expand_dims(image, axis=0)  # Add batch dimension

def predict_image(image):
    """Predict the class of a traffic sign image."""
    preprocessed_image = preprocess_image(image)
    prediction = model.predict(preprocessed_image)
    predicted_class = np.argmax(prediction, axis=1)[0]
    return classes[predicted_class]
    
with gr.Blocks(theme='ParityError/Interstellar', title="Traffic Sign Classifier") as demo:
    with gr.Column():
            gr.HTML("<br><center><h1>🚦 Traffic Sign Classifier</h1></center><br>")
            gr.Markdown("""
            - The Traffic Sign Classifier predicts the class of a traffic sign image using the German Traffic Sign Recognition Benchmark (GTSRB) dataset. Upload an image of a traffic sign, and the model will predict its class.
            - The German Traffic Sign Recognition Benchmark (GTSRB) dataset is a comprehensive collection of traffic sign images used for a multi-class, single-image classification challenge. It was introduced at the International Joint Conference on Neural Networks (IJCNN) 2011 to foster research in image classification without requiring specialized domain knowledge. The dataset includes more than 50,000 images spanning over 40 classes, providing a realistic and varied set of traffic signs encountered in everyday driving scenarios.
            """)
    with gr.Row():
        with gr.Column():
            image = gr.Image(type="pil", label="Upload Traffic Sign Image", image_mode="RGB", height=300)
                
        with gr.Column():
            textbox = gr.Textbox(label="Predicted Class", lines=8.9) 
            button = gr.Button("🚀 Launch Classifier", variant='primary')      

        predicted_class = button.click(predict_image, inputs=image, outputs=textbox)
  
demo.queue()  # Required to yield the streams from the text generation
demo.launch(inbrowser=True)
